# DNS SEED CONSTANTS
ENTRY_DURATION = 60*60*24*1 #duration in seconds
SEED_SERVER_URL = "http://localhost:8080"
SEED_SERVER_PORT = 8080

#MINER CONSTANTS
MINER_SERVER_PORT = 9000
MINER_VERSION = "0.1"

# DB constants
BLOCK_DB_LOC = "db/block.db"